# Generated by Django 4.2.29 on 2026-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
