# Generated by Django 4.2.29 on 2026-04-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0002_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
