# Generated by Django 4.2.29 on 2026-04-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog2", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
    ]
